---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
  namespace: registry
data:
  htpasswd: |
    cicd:$2y$10$LXdO4A.Do1.38f4MkeexVuoHK9xgciMcxog0w/2fLnk1u0z/tahV2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-vol
  namespace: registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: registry
  name: registry
  namespace: registry
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - env:
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /auth/htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: Registry Realm
        image: registry:2
        name: registry
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: auth
            mountPath: /auth
          - name: images
            mountPath: /var/lib/registry
      volumes:
        - name: auth
          configMap:
            name: auth
        - name: images
          persistentVolumeClaim:
            claimName: registry-vol
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
  namespace: registry
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 5000
      nodePort: 30172
  selector:
    app: registry
